export const USER_REQUEST = "USER_REQUEST";

export const USER_REQUEST_FAILURE = "USER_REQUEST_FAILURE";

export const USER_REQUEST_SUCCESS = "USER_REQUEST_SUCCESS";

export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";



